[mypy]
# Configuración para que Mypy encuentre tus archivos en 'src'
python_version = 3.10
mypy_path = src
explicit_package_bases = True
namespace_packages = True

# Reglas de rigor
disallow_untyped_defs = True
ignore_missing_imports = True
check_untyped_defs = True

# Evita que errores viejos se queden en memoria
incremental = False